# Descarga e instalacion de librerias y archivos a utilizar

In [4]:
pip install gdown

SyntaxError: invalid syntax (487001140.py, line 1)

In [5]:
pip install pandas

Collecting pandas
  Downloading pandas-3.1.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (18 kB)
Collecting numpy>=2.0.2 (from pandas)
  Downloading numpy-2.5.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.9.0 in ./env/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./env/lib/python3.12/site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)
Downloading pandas-3.1.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 15.3 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Downloading numpy-2.5.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 13.2 MB/s eta 0:00:00m eta 0:00:010:01:01
Installing collected packages: numpy, pandas
Successfully installed numpy-2.5.4 pandas-3.1.0
Note: you may need to restart the kernel to use updated packages.

In [7]:
!pip install sweetviz

Collecting sweetviz
  Using cached sweetviz-2.3.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in ./env/lib/python3.12/site-packages (from sweetviz) (3.1.0)
Requirement already satisfied: numpy>=1.16.0 in ./env/lib/python3.12/site-packages (from sweetviz) (2.5.4)
Collecting matplotlib>=3.1.3 (from sweetviz)
  Using cached matplotlib-3.11.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (80 kB)
Requirement already satisfied: tqdm>=4.43.0 in ./env/lib/python3.12/site-packages (from sweetviz) (4.70.1)
Collecting scipy>=1.3.2 (from sweetviz)
  Using cached scipy-1.18.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Requirement already satisfied: jinja2>=2.11.1 in ./env/lib/python3.12/site-packages (from sweetviz) (3.1.6)
Collecting importlib_resources>=1.2.0 (from sweetviz)
  Using cached importlib_resources-7.1.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: MarkupSafe>=2.0 in ./env/lib/python3.12/site-packages (from jinja2>=2.11.1->sweetviz) (3.0.4)
Collecting contourpy>=1.0.1 (from matplotlib>=3.1.3->sweetviz)
  Using cached contourpy-1.4.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib>=3.1.3->sweetviz)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib>=3.1.3->sweetviz)
  Downloading fonttools-4.67.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (137 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.2/137.2 kB 2.2 MB/s eta 0:00:00[31m1.9 MB/s eta 0:00:01
Collecting kiwisolver>=1.3.1 (from matplotlib>=3.1.3->sweetviz)
  Using cached kiwisolver-1.5.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in ./env/lib/python3.12/site-packages (from matplotlib>=3.1.3->sweetviz) (26.3)
Collecting pillow>=9 (from matplotlib>=3.1.3->sweetviz)
  Downloading pillow-13.0.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting pyparsing>=3 (from matplotlib>=3.1.3->sweetviz)
  Using cached pyparsing-3.3.3-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: python-dateutil>=2.7 in ./env/lib/python3.12/site-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./env/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)
Using cached sweetviz-2.3.3-py3-none-any.whl (15.1 MB)
Using cached importlib_resources-7.1.0-py3-none-any.whl (37 kB)
Using cached matplotlib-3.11.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (9.9 MB)
Using cached scipy-1.18.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.3 MB)
Using cached contourpy-1.4.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (383 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.67.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 14.5 MB/s eta 0:00:00m eta 0:00:010:01:01
Using cached kiwisolver-1.5.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.5 MB)
Downloading pillow-13.0.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (7.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 15.2 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Using cached pyparsing-3.3.3-py3-none-any.whl (126 kB)
Installing collected packages: scipy, pyparsing, pillow, kiwisolver, importlib_resources, fonttools, cycler, contourpy, matplotlib, sweetviz
Successfully installed contourpy-1.4.0 cycler-0.12.1 fonttools-4.67.0 importlib_resources-7.1.0 kiwisolver-1.5.1 matplotlib-3.11.2 pillow-13.0.0 pyparsing-3.3.3 scipy-1.18.1 sweetviz-2.3.3

In [9]:
import os
import gdown

# ID extraído de tu enlace de Google Drive
file_id = "1ENXJDLDOoANo7pZgBvTFCRvImVSwXQ1J"
url = f"https://drive.google.com/uc?id={file_id}"

# Nombre con el que se guardará el archivo en tu carpeta local
filename = "calendar.csv.gz"

# Verificamos si ya existe localmente antes de descargar
if not os.path.exists(filename):
  print(f"Descargando {filename} desde Google Drive...")
  gdown.download(url, filename, quiet=False)
else:
  print(f"El archivo '{filename}' ya existe en el directorio local!")

El archivo 'calendar.csv.gz' ya existe en el directorio local!

In [12]:
import os
import gdown

# ID extraído de tu enlace de Google Drive
file_id = "1JMwdMy8mXA8OgIH9O_6LmbxnWJ7h7e3X"
url = f"https://drive.google.com/uc?id={file_id}"

# Nombre con el que se guardará el archivo en tu carpeta local
filename = "listings.csv.gz"

# Verificamos si ya existe localmente antes de descargar
if not os.path.exists(filename):
  print(f"Descargando {filename} desde Google Drive...")
  gdown.download(url, filename, quiet=False)
else:
  print(f"El archivo '{filename}' ya existe en el directorio local!")

El archivo 'listings.csv.gz' ya existe en el directorio local!

# Lectura y descarga de archivos

In [13]:
import pandas as pd

# Leemos el archivo con Pandas
df_calendar = pd.read_csv("calendar.csv.gz")
df_calendar.head()

   listing_id        date available  minimum_nights  maximum_nights
0       11508  2026-06-30         f               3            1125
1       11508  2026-07-01         f               3            1125
2       11508  2026-07-02         f               3            1125
3       11508  2026-07-03         f               3            1125
4       11508  2026-07-04         f               3            1125

In [14]:
import pandas as pd

# Leemos el archivo con Pandas
df_listings = pd.read_csv("listings.csv.gz")
df_listings.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,54019695,https://www.airbnb.com/rooms/54019695,20260629030533,2026-07-02,city scrape,Hermoso departamento con piscina en Puerto Mad...,Enjoy a stylish experience in this centrally-l...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,298874610,...,NaN,NaN,NaN,NaN,NaN,24,24,0,0,NaN
1,41720307,https://www.airbnb.com/rooms/41720307,20260629030533,2026-06-29,city scrape,"Departamento dos ambientes, 2cuadras recoleta ...",Brand new remodeled apartment 2 blocks from th...,NaN,https://a0.muscache.com/pictures/37e687e2-2587...,220409424,...,4.67,4.67,4.56,NaN,NaN,8,8,0,0,0.16
2,1090530711732696379,https://www.airbnb.com/rooms/1090530711732696379,20260629030533,2026-07-02,previous scrape,"alquiler mensual ,escenografico.",This place is strategically located - it will ...,NaN,https://a0.muscache.com/pictures/3adbe27a-af59...,488443857,...,4.67,5.00,4.67,NaN,NaN,3,1,2,0,0.34
3,1482653002662185299,https://www.airbnb.com/rooms/1482653002662185299,20260629030533,2026-07-02,city scrape,Descanso ideal - Av. Sante Fe,"Large and comfortable apartment for 4 people, ...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,283840529,...,4.95,4.89,4.89,NaN,NaN,12,12,0,0,1.78
4,1046394538968941382,https://www.airbnb.com/rooms/1046394538968941382,20260629030533,2026-06-29,city scrape,Excelente zona,Enjoy easy access to everything from this perf...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,550970409,...,NaN,NaN,NaN,NaN,NaN,1,0,1,0,NaN

In [ ]:
import sweetviz as sv

# 4. Generar y guardar el reporte automatizado con Sweetviz
reporte = sv.analyze(df_obesidad)
reporte.show_html("reporte_obesidad_sweetviz.html")
reporte.show_notebook()